# Layer configuration for meta-home-monitor
BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "home-monitor"
BBFILE_PATTERN_home-monitor = "^${LAYERDIR}/"
BBFILE_PRIORITY_home-monitor = "10"

LAYERDEPENDS_home-monitor = " \
    core \
    meta-python \
    networking-layer \
    multimedia-layer \
    webserver \
    raspberrypi \
    "
LAYERSERIES_COMPAT_home-monitor = "scarthgap"
